global:
  scrape_interval: 5s

scrape_configs:

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Flask APIs
  - job_name: "retro-api"
    static_configs:
      - targets:
          - api1:5000
          - api2:5000

  # Nginx exporter
  - job_name: "nginx"
    static_configs:
      - targets:
          - nginx-exporter:9113

  # Kafka exporter
  - job_name: "kafka"
    static_configs:
      - targets:
          - kafka-exporter:9308

  # Postgres exporter
  - job_name: "postgres"
    static_configs:
      - targets:
          - postgres-exporter:9187