global:
  scrape_interval: 5s

scrape_configs:

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Flask APIs
  - job_name: "retro-api"
    static_configs:
      - targets:
          - api1:5000
          - api2:5000

  # Nginx exporter
  - job_name: "nginx"
    static_configs:
      - targets:
          - nginx-exporter:9113

  # Kafka exporter
  - job_name: "kafka"
    static_configs:
      - targets:
          - kafka-exporter:9308

  # Postgres exporter
  - job_name: "postgres"
    static_configs:
      - targets:
          - postgres-exporter:9187

  - job_name: "redis"
    static_configs:
      - targets:
          - redis-exporter:9121


# GRAFANA DASHBOARD QUERIES (for reference):

# API Request Rate - sum(rate(http_requests_total[1m])) by (endpoint)

# Kafka Topic Activity - sum(kafka_topic_partition_current_offset) by (topic)

# Nginx Request Rate - rate(nginx_http_requests_total[1m])

# PostgreSQL Active Connections - pg_stat_database_numbackends